import:
  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml
  #- ~/.config/alacritty/catppuccin/catppuccin-mocha.yml

window:
  option_as_alt: Both

env:
  TERM: xterm-256color

font:
        normal:
                family: "Jetbrains Mono"
        size: 17.0
