import:
  - ~/.config/alacritty/catppuccin/catppuccin-latte.yml

window:
  option_as_alt: Both

env:
  TERM: xterm-256color

font:
        normal:
                family: "Jetbrains Mono"
        size: 18.0
