#! /bin/sh

#
#	Download a video from youtube in mp3
#	upload it to google drive
#

cd /tmp

youtube-dl -x --audio-format mp3 --audio-quality 0 \
	-o '%(title)s.%(ext)s' \
	--exec 'dropbox_uploader.sh -p upload {} /Wanie && rm -f {}' $1
